spring:
  profiles:
    active: ${APP_PROFILE:dev}
  devtools:
    add-properties: false
  main:
    banner-mode: "CONSOLE"   # por algum motivo tem que ser entre aspas duplas
    allow-bean-definition-overriding: true  
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://root:MongoDB2025!@localhost:27017/inventory-service?authSource=admin
      database: product-service
      auto-index-creation: true
      uuid-representation: standard
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8061

logging:
  level:
    org.springframework.data.mongodb: INFO
    br.matosit.customer_service: INFO
  pattern: 
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [X-ReqID=%X{X-ReqId}] [%-5level] [%logger{70}] - %msg%n"

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

springdoc:
  api-docs:
    path: "/api-docs"

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 
     
webclient:
  product:
    base-url: http://localhost:8051 
